### ISSUE TITLE
Top element is page title displays category and not article title

### ISSUE THREAD

**Issue by johanpeters** [kevinsguides/auto-scrollspy#6]
Hello,
when Top element is page title is enabled it shows the category name and not the page page title (article name).

example
url: domain.com/about/privacy 

top element is page title enabled: it displays about
it should be privacy

**Comment by kevinsguides** [comment]
I think I've fixed this for next release. I will hopefully have it out tomorrow with updated option for scroll offset. Clearly I need to improve my testing practices. Thanks for helping!

Commits pushed for title fix are done in autoscrollspy.php if you want to manually test

**Comment by johanpeters** [comment]
Hello Kevin,
greate to hear.. and happy to help, test and do my part of making this
even better than before.

i still looking a way to make the module sticky..
the floating works but understandable its floating over the text.

sticky module setting does not work in combination of Gantry5 ..
only way i know is to make a section sticky.. but that is not what is
should be.
